### ISSUE TITLE
Icon Selector not appearing

### ISSUE THREAD

**Issue by ncodee** [zixpo/candybar#10]
Hi, great work with project!

I've just recently migrated to your repo, but I'm having an issue with the manual Icon Selector not showing in apps like Nova launcher. It was working previously on the master repo, but now it stopped working. I've checked the drawbles and appfilters and they are fine, just wondering if I'm doing something wrong or there is an issue with source?

Thanks.

**Comment by sarsamurmu** [comment]
I think you're doing something wrong, it's working fine with me.

**Comment by sarsamurmu** [comment]
I think you're doing something wrong, it's working fine with me.

**Comment by sarsamurmu** [comment]
I think you're doing something wrong, it's working fine with me.

**Comment by ncodee** [comment]
> I think you're doing something wrong, it's working fine with me.

Hmm, icon is appearing under Common in Nova launcher, but the app is not listed in the icon picker. I'm not sure what it is, as I hadn't modified anything except from appfilter and drawables.

Maybe someone else is having the same issue?

**Comment by ncodee** [comment]
Fixed the issue, it seems there was an added feature to the 'AndroidManifest.xml' that was set to 'false' on default, which prevented the Icon Picker being accessible to other launchers.

` <!-- Set `android:enabled="false"` to `android:enabled="true"` below if you don't want your app to be locked until opened.-->`

Description is quite vague on what it does, should explain what 'locked' state does.
