### ISSUE TITLE
Fix NullPointerException in fast scroller popup

### ISSUE THREAD

**Issue by sarsamurmu** [zixpo/candybar#105]
It looks like this line is causing the exception - https://github.com/zixpo/candybar/blob/main/library/src/main/java/candybar/lib/fragments/IconsFragment.java#L117

Do some null checks!

**Comment by randomvector** [comment]
I've managed to recreate the crash for this issue via launching the icon pack via Nova Launcher (when you hold down the icon and select edit>select icon pack). If you launch the icon pack (as shown below):
![icon_launcher_via nova](https://user-images.githubusercontent.com/27604724/209872457-7b57a368-0adf-4b31-a2e5-4477c03cdd87.png)
The icon pack will launch and try to load the icons and eventually crash. This crash occurs if you set "show_icon_name" to false in dashboard_configurations. Setting "show_icon_name" to true no crashing occurs when using the icon selector. I am using Candybar version 3.16.1. I've included the crashlog below:
[crashlog.txt](https://github.com/zixpo/candybar/files/10316480/crashlog.txt)
