### ISSUE TITLE
Clock Widget Don't Work 

### ISSUE THREAD

**Issue by anarchist22** [zixpo/candybar#106]
Since version 3.16 the clock widget has disappeared

**Comment by Donnnno** [comment]
If you want to use the clock widget again, you should enable here in the manifest:

https://github.com/zixpo/candybar/blob/6d38ede157f58b16fcf46304d55d59b2f13e0d26/app/src/main/AndroidManifest.xml#L204-L216

**Comment by anarchist22** [comment]
I already figured it out, but thanks for taking the time to reply.

**Comment by anarchist22** [comment]
I already figured it out, but thanks for taking the time to reply.
