### ISSUE TITLE
Icon search not working when editing manually

### ISSUE THREAD

**Issue by Bethanielle** [zixpo/candybar#114]
Just opening the Pack and using the search function works fine.

When editing a single icon manually: 
- long tap
- edit
- open the pack with the 'external link' icon

Then using the search function, it will find no icons.

This is happening since the last update, on Nova Launcher.

**Comment by moertel** [comment]
I'm using Nova 7.0.57 and Candybar 3.16.2 on a phone with Android 13 and for me the steps you describe work as they should. Just to double-check:

 * Long-tap an icon in the app drawer
 * Tap the pencil
 * Tap the icon
 * Choose your icon pack
 * Tap the `[↗]` icon at the top right
 * Open the search 🔎
 * Type something

For me this yields results in the icon search (provided I have icons that match the search).

**Comment by Bethanielle** [comment]
If this can help, this is the logcat sent by a user

`03-04 15:22:50.366 26578 26578 E Australis: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.String.toLowerCase(java.util.Locale)' on a null object reference
03-04 15:22:50.366 26578 26578 E Australis:     at o.cx.R(SourceFile:43)
03-04 15:22:50.366 26578 26578 E Australis:     at o.nx.b2(SourceFile:3)
03-04 15:22:50.366 26578 26578 E Australis:     at o.nx.T1(Unknown Source:0)
03-04 15:22:50.366 26578 26578 E Australis:     at o.nx$c.j(SourceFile:87)
03-04 15:22:50.366 26578 26578 E Australis:     at o.j6.h(Unknown Source:4)
03-04 15:22:50.366 26578 26578 E Australis:     at o.j6.b(Unknown Source:0)
03-04 15:22:50.366 26578 26578 E Australis:     at o.i6.run(Unknown Source:4)
03-04 15:22:50.366 26578 26578 E Australis:     at android.os.Handler.handleCallback(Handler.java:938)
03-04 15:22:50.366 26578 26578 E Australis:     at android.os.Handler.dispatchMessage(Handler.java:99)
03-04 15:22:50.366 26578 26578 E Australis:     at android.os.Looper.loopOnce(Looper.java:201)
03-04 15:22:50.366 26578 26578 E Australis:     at android.os.Looper.loop(Looper.java:288)
03-04 15:22:50.366 26578 26578 E Australis:     at android.app.ActivityThread.main(ActivityThread.java:7833)
03-04 15:22:50.366 26578 26578 E Australis:     at java.lang.reflect.Method.invoke(Native Method)
03-04 15:22:50.366 26578 26578 E Australis:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
03-04 15:22:50.366 26578 26578 E Australis:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003) `

**Comment by Primokorn** [comment]
Candybar v3.16.2

- I open the dashbord, the search works but as soon as I hit the Back arrow, the screen is blank (I only see the Icons title). No more icons displayed.
- Same issue when editing an icon manually with Nova launcher

Android 13 - OxygenOS 13 - Oneplus 8 Pro

**Comment by sarsamurmu** [comment]
It was happening when `show_icon_name` was set to `false`. This issue has been fixed in `v3.18.1`
