### ISSUE TITLE
Billing Library Version Deprecation

### ISSUE THREAD

**Issue by atanusanyal** [zixpo/candybar#137]
![image](https://github.com/zixpo/candybar/assets/7301670/3e5f0860-ad2d-4b62-94a7-b94ed6c8f2c2)

**Comment by walrus543** [comment]
Which version of Candybar do you use?

**Comment by atanusanyal** [comment]
3.17.3

**Comment by walrus543** [comment]
Current Bililng Library: `api 'com.android.billingclient:billing:6.0.0'`
I don't have this warning for my apps.

**Comment by moertel** [comment]
Yeah, same, I don't have this warning for any of my apps either and am using 3.17.3. as well. Can you double-check you're actually on 3.17.3, @atanusanyal? If you are, are you perhaps accidentally overriding the dependency in your app-level Gradle file? As @walrus543 already pointed out, the default used in CandyBar is v6. https://github.com/zixpo/candybar/blob/9799528f54e6d5e1144fe514325f355a9edb8f73/library/build.gradle#L101

**Comment by atanusanyal** [comment]
Thanks mates, I yeah checked. Actually it doesn't sync properly. Now its showing 6.0.0
