### ISSUE TITLE
Support for Vector icons in the icons tab 

### ISSUE THREAD

**Issue by Donnnno** [zixpo/candybar#139]
Right now, there are two options for vector based icons: Adaptive & Layer-list. But one is missing, the default vector one. 

It would be great to have support for that, because it can help with keeping the appsize small.

(so icons with the <vector> attribute)

**Comment by dhanu-saud** [comment]
@Donnnno Vector icons does work, I have tested. Only issue is they won't display correctly in 'icons' section.

**Comment by Donnnno** [comment]
That's pretty interesting, I guess I should rename the title of the issue then :)

**Comment by sarsamurmu** [comment]
Can you give me an example vector icon file?

**Comment by Donnnno** [comment]
Of course! This one should do:

[android.zip](https://github.com/zixpo/candybar/files/11708022/android.zip)

**Comment by sarsamurmu** [comment]
Fixed in `v3.17.4`

**Comment by Donnnno** [comment]
Thank you so much for adding this!

**Comment by moertel** [comment]
Oooohhh, fantastic!!! Just so I understand correctly: this means instead of shipping icons as PNG files with my icon pack, I can ship vector drawables? Are there any implications of doing so, i.e. would there be any devices or versions that don't support this format?

**Comment by Donnnno** [comment]
Some older launchers probably don't support this such as openlauncher. But yeah, it's much better than PNG
