### ISSUE TITLE
Can't handle duplicate filenames

### ISSUE THREAD

**Issue by MiepHD** [zixpo/candybar#173]
If there are multiple icons in the same request (like gallery) the following files have a number added to the filename but this number isn't added to the names in the xml files.

Would make some things easier if this the names are already correct

**Comment by Donnnno** [comment]
It also doesn't help that the names gathered are often in the users language instead of the English locale (galleria for example)

**Comment by MiepHD** [comment]
Especially when has no latin charecters so you have to rename every file

**Comment by MiepHD** [comment]
The drawable attribute is still wrong for duplicate file names. It contains the name with file extension even though this does not work when you add it like that to the corresponding xml files.

(Please reopen)
