### ISSUE TITLE
ALL icons option

### ISSUE THREAD

**Issue by atanusanyal** [zixpo/candybar#177]
How to Disable "All icon" option from dashboard?

**Comment by sarsamurmu** [comment]
https://github.com/zixpo/candybar-sample/wiki/Advanced-dashboard-configurations#:~:text=setShowTabAllIcons(boolean)

**Comment by dalight13** [comment]
That option doesn't seem to work on my side, anything I could be doing wrong? Thanks I'm on 3.19.0

**Comment by atanusanyal** [comment]
> That option doesn't seem to work on my side, anything I could be doing wrong? Thanks I'm on 3.19.0

Just go to this and "false" it 

###  **configuration.setShowTabAllIcons(true)**


public class CandyBar extends CandyBarApplication {

    @NonNull
    @Override
    public Configuration onInit() {
        Configuration configuration = new Configuration();

        configuration.setGenerateAppFilter(true);
        configuration.setGenerateAppMap(true);
        configuration.setGenerateThemeResources(true);

        configuration.setNavigationIcon(NavigationIcon.STYLE_4);
        configuration.setNavigationViewHeaderStyle(NavigationViewHeader.NONE);

        configuration.setHomeGridStyle(GridStyle.FLAT);
        configuration.setApplyGridStyle(GridStyle.FLAT);
        configuration.setWallpapersGridStyle(GridStyle.FLAT);
        configuration.setRequestStyle(Style.PORTRAIT_FLAT_LANDSCAPE_FLAT);
        configuration.setAboutStyle(Style.PORTRAIT_FLAT_LANDSCAPE_FLAT);

        configuration.setShowTabAllIcons(true);
        configuration.setCategoryForTabAllIcons(new String[] {
                "Games", "Apps"
        });

        return configuration;
    }

**Comment by dalight13** [comment]
Yeah that's what I did on my side, look at my code + emulator execution of that code. I also get the same result on my phone. I also tried doing like you and limiting the categories we can see but that doesn't work either. Any idea? Thanks!

![image](https://github.com/zixpo/candybar/assets/7493814/c7fce49a-4cf1-4269-a3a0-b2ed15eb008e)

**Comment by dalight13** [comment]
I ended up downloading the whole library and realized this option didn't do what I thought it was. Sorry about my messages it works properly in the sample app. Thanks for your replies
