### ISSUE TITLE
Is it completely FLOSS

### ISSUE THREAD

**Issue by braniii** [zixpo/candybar#18]
I just found your impressive icon library and would like to use it for my icon theme to finally make it adaptive. I want to publish it to f-droid only so it needs to be completely FLOSS, see [f-droid policy](https://f-droid.org/en/docs/Inclusion_Policy/). Could you tell me, it this is the case?

Thx for your help and the great work.

**Comment by sarsamurmu** [comment]
Yeah, it's completely FLOSS.

**Comment by Donnnno** [comment]
Hi, in the past week, we've updated [Arcticons ](https://github.com/Donnnno/Arcticons)to the candybar dashboard, and it's great!
But we've also noticed some implementations are not FLOSS.
We had to remove things like billing, license checking, onesignal, proguard and some other stuff. But it builds with F-Droid now :^)

**Comment by sarsamurmu** [comment]
I was mistaken. I thought as long as you don't use billing or OneSignal, it would maintain F-droid policy. But it's not true.

Thanks for the update.

**Comment by Donnnno** [comment]
Yeah, F-Droid is really strict with these things, so all those things have to be completely turned off and removed.

**Comment by Donnnno** [comment]
Hi, Just wanted to let you know that I've created a fully foss fork for Candybar here :)
https://github.com/Donnnno/candybar-foss
https://github.com/Donnnno/candybar-foss-sample
