### ISSUE TITLE
New issue

### ISSUE THREAD

**Issue by atanusanyal** [zixpo/candybar#190]
![image](https://github.com/user-attachments/assets/c0b76355-15a5-419f-84d2-8e5ebd04e959)

**Comment by atanusanyal** [comment]
![image](https://github.com/user-attachments/assets/6227b16a-d6ed-4bf8-88d1-b3cf1ebaf2d9)

**Comment by atanusanyal** [comment]
![image](https://github.com/user-attachments/assets/1991cbb9-3c22-474d-995c-cb18166ff673)
Please fix this issue

**Comment by Donnnno** [comment]
You could just have opened the project in android studio and do it yourself, you know. 

It's literally hovering over the wiggly lines and applying the suggestions...

**Comment by atanusanyal** [comment]
> You could just have opened the project in android studio and do it yourself, you know.
> 
> It's literally hovering over the wiggly lines and applying the suggestions...

**Comment by atanusanyal** [comment]
Could please provide the details to fix this issue

**Comment by Donnnno** [comment]
Please have a bit of patience, we'll have to wait for the pr to be merged, and for a release to be created.

The alternative is for you to fork and use your own implementation.

**Comment by atanusanyal** [comment]
Thanks . Waiting for next update release
