### ISSUE TITLE
App update rejected due to Deceptive ads

### ISSUE THREAD

**Issue by nyxtheslayer** [zixpo/candybar#195]
Just got my app update rejected due to Issue found: Violation of Deceptive Ads policy
![Screenshot_20240817-224335](https://github.com/user-attachments/assets/153a9050-1893-494e-afb0-e85989ff6e79)

**Comment by Donnnno** [comment]
Please provide their actual attachment

**Comment by nyxtheslayer** [comment]
Here is the full email and the screenshot that google provided
![IN_APP_EXPERIENCE-4627](https://github.com/user-attachments/assets/10a026ae-c08e-4f3f-b308-e2ca90bd12e1)
![Screenshot_20240817-233323](https://github.com/user-attachments/assets/b815b0e6-4d6d-4d0e-9601-46abb1018485)
![Screenshot_20240817-233352](https://github.com/user-attachments/assets/56d05d27-f9b1-4b68-bce4-d327a9a4ffa0)

**Comment by kshitijdeota** [comment]
As far as my knowledge and past experience with play store, if you are advertising WallNode on your icon pack (even with just a screenshot), you should  not do so. No such advertising is allowed even if the advertisement is one of your own apps. Many do it until their app is flagged (caught by a screening bot). You may say in the app, for example: "Look for my wallpaper app WallNode" in plain text (no link).

**Comment by Donnnno** [comment]
If the app prompts you to download another app to download wallpapers, instead of showing them in-app, it's deceptive according to Google. Especially given the fact that Candybar has a built-in wallpaper function.
