### ISSUE TITLE
can't disable regular icon request

### ISSUE THREAD

**Issue by atanusanyal** [zixpo/candybar#23]
![image](https://user-images.githubusercontent.com/7301670/88306399-4d732880-cd28-11ea-951a-991b063c6a39.png)

**Comment by sarsamurmu** [comment]
I will look into it

**Comment by atanusanyal** [comment]
when someone in-app purchase it only then this problem happen. Then the premium icon request and regular icon request both showing up, although i disable the regular icon request.
