### ISSUE TITLE
There is lots of bugs please fix it

### ISSUE THREAD

**Issue by atanusanyal** [zixpo/candybar#24]
1. Regular icon request not working properly, sometime its works sometimes don't 
2. Wallpaper cloud didn't  sync properly its doesn't work. Just blank in wallpaper section

**Comment by sarsamurmu** [comment]
For wallpaper check this out - https://github.com/zixpo/candybar-sample/wiki/Migrating-from-old-CandyBar#migrating-to-new-wallpaper-json-structure

**Comment by atanusanyal** [comment]
Yes, now wallpapers working. Thanks
