### ISSUE TITLE
Tighter Android integration

### ISSUE THREAD

**Issue by mcandre** [zixpo/candybar#30]
Could there be an Android API for overriding icons during splash screen loading?

Especially to force splash screens to apply dark mode!

**Comment by sarsamurmu** [comment]
Are you talking about the splash screen's icon? If so, then you can replace it, [read the wiki](https://github.com/zixpo/candybar-sample/wiki/Changing-the-app's-icons#splash-screen-icon).

I will work on the dark mode of splash screen.

**Comment by sarsamurmu** [comment]
It's now possible with the `-night` resource directory
