### ISSUE TITLE
Support for Niagara Launcher (?)

### ISSUE THREAD

**Issue by Martin5001** [zixpo/candybar#31]
I don't know whether there is no support for Niagara Launcher or it's just that the icon pack uses older version of Candybar.
So if it's not supported, I'd like to ask you to add it. (More info can be found in [Niagara Launcher Documentation](https://help.niagaralauncher.app/article/24-resources-for-icon-pack-developers).) Otherwise I'll contact the icon pack maker.

**Comment by sarsamurmu** [comment]
Niagara launcher is supported since [`v3.7.0`](https://github.com/zixpo/candybar/blob/master/CHANGELOG.md#v370).
