### ISSUE TITLE
Update to Billing Library 3

### ISSUE THREAD

**Issue by atanusanyal** [zixpo/candybar#37]
![Screenshot 2021-03-06 152342](https://user-images.githubusercontent.com/7301670/110202665-3dabed00-7e90-11eb-8924-5fb375459c87.jpg)

**Comment by atanusanyal** [comment]
Please update Google Play Billing Library version 3

**Comment by INayra** [comment]
Ok

Enviado do meu Samsung Mobile da Claro
Obter o Outlook para Android<https://aka.ms/ghei36>

________________________________

**Comment by sarsamurmu** [comment]
Available in `v3.10.0`

**Comment by atanusanyal** [comment]
Thank you so much, I want to donate little much for yours work, please tell me where to donate

**Comment by sarsamurmu** [comment]
Just install it from [Play store](https://play.google.com/store/apps/details?id=com.candybar.dev) and buy a donation or premium request.

**Comment by atanusanyal** [comment]
so denotation from Candybar Dev app?

**Comment by sarsamurmu** [comment]
Yes

**Comment by atanusanyal** [comment]
how to fix this?
![image](https://user-images.githubusercontent.com/7301670/121233105-e878e080-c8af-11eb-9c62-2a1768666635.png)

**Comment by sarsamurmu** [comment]
Update your Android Studio to 4.2
