### ISSUE TITLE
can't find symbol variable version name after updating gradle 

### ISSUE THREAD

**Issue by atanusanyal** [zixpo/candybar#39]
![Screenshot 2021-03-11 201539](https://user-images.githubusercontent.com/7301670/110805178-dd111b80-82a6-11eb-99ae-27b7f0d73090.jpg)

**Comment by INayra** [comment]
Nossa assim fica difícil em.

Enviado do meu Samsung Mobile da Claro
Obter o Outlook para Android<https://aka.ms/ghei36>

________________________________
From: atanusanyal ***@***.***>
Sent: Thursday, March 11, 2021 10:49:21 AM
To: zixpo/candybar ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [zixpo/candybar] can't find symbol variable version name after updating gradle (#39)


[Screenshot 2021-03-11 201539]<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F7301670%2F110805178-dd111b80-82a6-11eb-99ae-27b7f0d73090.jpg&data=04%7C01%7C%7C1c9f126d22bf4ec789cc08d8e49cdbce%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637510709640142527%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=bTNT1Q%2FwjxbgApJ0z%2BT1P4tYHpBFbN7p2vXJpTf2X%2Bo%3D&reserved=0>

**Comment by sarsamurmu** [comment]
Add this line to `library/build.gradle` file - https://github.com/zixpo/candybar/blob/main/library/build.gradle#L39

**Comment by INayra** [comment]
Rest

Enviado do meu Samsung Mobile da Claro
Obter o Outlook para Android<https://aka.ms/ghei36>

________________________________

**Comment by atanusanyal** [comment]
Please update Google Play Billing Library  version to 3

**Comment by sarsamurmu** [comment]
Would do it before the deadline

**Comment by INayra** [comment]
would you pay?

Enviado do meu Samsung Mobile da Claro
Obter o Outlook para Android<https://aka.ms/ghei36>

________________________________
