### ISSUE TITLE
please update

### ISSUE THREAD

**Issue by atanusanyal** [zixpo/candybar#41]
![image](https://user-images.githubusercontent.com/7301670/114824531-a5841a80-9de2-11eb-9723-c17556d4cb75.png)

**Comment by sarsamurmu** [comment]
Fixed in `v3.9.2`

**Comment by atanusanyal** [comment]
Thank you very much and What Update to Billing Library 3?

**Comment by sarsamurmu** [comment]
I would do it before the deadline.
