### ISSUE TITLE
Newlines in E-Mail get removed by Samsung Mail

### ISSUE THREAD

**Issue by leifniem** [zixpo/candybar#46]
I noticed this issue when parsing mails with python and it seems to be a problem exclusively with Samsung Mail.

The content of the mail ends up without any whitespace between essential information, looking like this:
```
Manufacturer : samsungModel : SM-G998UProduct : p3qsqwScreen Resolution : 1440 x 2920 pixelsAndroid Version : 11App Version : 1.5.8 RCandyBar Version : 3.11.7Remindcom.remind101/com.remind101.splash.SplashActivityhttps://play.google.com/store/apps/details?id=com.remind101
```

I don't know if simply switching from `\n` to `\r\n` will be able to fix this problem, but it makes organizing 1000+ requests pretty tedious.

The code related to this would be both RequestBuilder classes:

https://github.com/zixpo/candybar/blob/be5c7318a600a966867542fb154a07011b9a1ba3/library/src/main/java/candybar/lib/tasks/IconRequestBuilderTask.java#L120-L126

https://github.com/zixpo/candybar/blob/be5c7318a600a966867542fb154a07011b9a1ba3/library/src/main/java/candybar/lib/tasks/PremiumRequestBuilderTask.java#L82-L94

Thanks for all your work on this project ☺

**Comment by sarsamurmu** [comment]
In `v3.12.0`, `\r\n` is being used as line endings instead of just `\n`. This would probably fix your problem.

**Comment by leifniem** [comment]
Thanks a lot! i hope the fix really is that simple.

**Comment by sarsamurmu** [comment]
Please let me know if this doesn't work. I may have another fix.

**Comment by leifniem** [comment]
I'll talk to Deltas current maintainer that we check for it :)
