### ISSUE TITLE
Problems in the AndroidManifest.xml

### ISSUE THREAD

**Issue by Etny00** [zixpo/candybar#47]
After updating to Android Studio version 2020.3.1 I get this error in the AndroidManifest.xml
- Cannot resolve symbol '@style/AppTheme'
- Cannot resolve symbol '@style/SplashTheme'
- Cannot resolve symbol '@style/AppTheme'

**Comment by sarsamurmu** [comment]
Follow this update guide - https://github.com/zixpo/candybar-sample/wiki/Updating-the-dashboard#from-v3101-to-v3110
