### ISSUE TITLE
Please change App version method 

### ISSUE THREAD

**Issue by atanusanyal** [zixpo/candybar#48]
Please change app version method, bring back old method. 
![image](https://user-images.githubusercontent.com/7301670/128546557-a5ff4718-2d3c-4430-bf31-5c1dd1ebf516.png)

**Comment by sarsamurmu** [comment]
Well, looks like you're using the development build. You're supposed to use the sample version.

Anyway, just change [these lines](https://github.com/zixpo/candybar/blob/main/app/build.gradle#L34-L35) to how you want your version code and version number to be. For example see [this](https://github.com/zixpo/candybar-sample/blob/main/app/build.gradle#L22-L23)
