### ISSUE TITLE
Icons being randomly assigned on OPPO Launcher

### ISSUE THREAD

**Issue by wokija** [zixpo/candybar#51]
Hi,

Since updating to latest CandyBar release, I've gotten reports about icons being randomly applied to apps on OPPO phones using stock launcher. Clearing app data / cache and rebooting phone do not fix the issue.

**Comment by sarsamurmu** [comment]
I don't think the dashboard would cause this. Try checking other things that might cause the problem.

**Comment by wokija** [comment]
Haven't gotten any more reports about this so I'll close the issue for now. Might have been fixed after an OPPO update.
