### ISSUE TITLE
Overwrite play store link

### ISSUE THREAD

**Issue by Aman9das** [zixpo/candybar#54]
https://github.com/zixpo/candybar/blob/cb02c37125a9cc15ef74b68d73ef0b91c5fa5941/library/src/main/java/candybar/lib/tasks/IconRequestBuilderTask.java#L125

For arcticons we provide fdroid apps as well as playstore apps
Is it possible to have the email send play store link if the app was installed from play-store and f-droid link when installed from f-droid

**Comment by sarsamurmu** [comment]
You can modify the email body using dashboard configurations. See this wiki - https://github.com/zixpo/candybar-sample/wiki/Dashboard-configurations#custom-email-body-generator.

If you're having problem writing the Java code, just let me know, I will try to help you with that.

**Comment by Aman9das** [comment]
Thank you so much, we were dumb, we added the whole library manually 😖

But it gives more choice, so it's alright hopefully..

**Comment by sarsamurmu** [comment]
Just in case you need it. You can use it as a reference.

```java
package com.candybar.dev.applications;
//             TODO: ^^^ Change it your package name

import android.content.pm.PackageManager;

import androidx.annotation.NonNull;

import candybar.lib.applications.CandyBarApplication;
import candybar.lib.items.Request;

// TODO: Remove `//` below to enable OneSignal
//import com.onesignal.OneSignal;

public class CandyBar extends CandyBarApplication {

    // TODO: Remove `/*` and `*/` below to Enable OneSignal
    /*
    @Override
    public void onCreate() {
        super.onCreate();

        // OneSignal Initialization
        OneSignal.initWithContext(this);
        OneSignal.setAppId("YOUR_ONESIGNAL_APP_ID_HERE");
    }
    */

    @NonNull
    @Override
    public Configuration onInit() {
        Configuration configuration = new Configuration();

        configuration.setGenerateAppFilter(true);

        configuration.setEmailBodyGenerator(requests -> {
            PackageManager packageManager = getApplicationContext().getPackageManager();
            StringBuilder emailBody = new StringBuilder();
            boolean first = true;

            for (Request request : requests) {
                if (!first) {
                    emailBody.append("\r\n\r\n");
                } else {
                    first = false;
                }

                emailBody.append(request.getName())
                        .append("\r\n")
                        .append(request.getActivity())
                        .append("\r\n");

                String installerPackage = packageManager.getInstallerPackageName(request.getPackageName());

                if (installerPackage != null && installerPackage.equals("com.android.vending")) {
                    emailBody.append("https://play.google.com/store/apps/details?id=")
                            .append(request.getPackageName());
                } else {
                    emailBody.append("https://f-droid.org/en/packages/")
                            .append(request.getPackageName()).append("/");
                }
            }

            return emailBody.toString();
        });

        return configuration;
    }
}

```

**Comment by Aman9das** [comment]
You're amazing! Thank you so much..

**Comment by Aman9das** [comment]
> Task :app:compileDarkDebugJavaWithJavac
Note: E:\Aman\Programs\Arcticons\app\src\main\java\com\donnnno\arcticons\applications\CandyBar.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

It runs, but you'd want to check this

**Comment by sarsamurmu** [comment]
You can ignore that or change the line to match this
```java
@SuppressWarnings("deprecation")
String installerPackage = packageManager.getInstallerPackageName(request.getPackageName());
```

**Comment by Aman9das** [comment]
Thanks btw we have added date widget, and digital clock widget, do you want them ..?

**Comment by Aman9das** [comment]
Also now we have a Foss version of the library in our repo.. do you want to host it as candybar foss?

**Comment by sarsamurmu** [comment]
I will have to think about the Foss version. Also, it won't be a problem, I can modify the main library to make a foss compliant variant.

Anyway, Thanks for the offer and for letting me know that there can be a Foss version :D

**Comment by Aman9das** [comment]
Closing this.. as issue is resolved. Thanks again!
