### ISSUE TITLE
Wrong icons shown on One pluss launcher

### ISSUE THREAD

**Issue by zemzale** [zixpo/candybar#61]
In One Plus launcher you can set custom icons for individual apps. The problem is that if you try to do it, it shows only Gmail icon multiple times.

I can try to provide more info/screen if needed.

**Comment by teyri** [comment]
I will be very grateful if you provide screenshots or video.On Nov 9, 2021 16:45, zemzale ***@***.***> wrote:
In One Plus launcher you can set custom icons for individual apps. The problem is that if you try to do it, it shows only Gmail icon multiple times.
I can try to provide more info/screen if needed.

**Comment by zemzale** [comment]
![Screenshot_20211110-130947.jpg](https://user-images.githubusercontent.com/14844365/141102853-55f22722-d5f9-44a9-9f29-70c0589ca495.jpg)

![Screenshot_20211110-131004.jpg](https://user-images.githubusercontent.com/14844365/141102885-911d85ff-d214-4ae3-89f3-f9f1adff907a.jpg)

![Screenshot_20211110-131245.jpg](https://user-images.githubusercontent.com/14844365/141103189-2817043b-cbd0-47a0-bace-e4c2bedd928c.jpg)

In the first screenshot u can see that there is a button on the icon. If u press it you can select icon paks installed on the phone, and select an icon from there. 

In second screenshot you can see that only gmail icons are showed and they are shown multiple times.

The third screenshot shows how it looks with the builtin icon packs.

**Comment by sarsamurmu** [comment]
Did you update your `drawable.xml` and `appfilter.xml` located in `assets` directory?

**Comment by zemzale** [comment]
I indeed forgot to fill out those. This fixed the problem. Thanks for the help. Closing the issue.
