### ISSUE TITLE
Adding name attribute inside drawable.xml files causes a mess in bugs report file broken_drawables.xml

### ISSUE THREAD

**Issue by wokija** [zixpo/candybar#63]
We've added custom names for all icons after your suggestion to add a `name` attribute inside `drawable.xml` files. To make sorting easier, we also put the `name` attribute before the `drawable` one.

However, it came to my attention that the generated `broken_drawables.xml` from bugs report uses the first found attribute of each line as drawable name, resulting in most lines being detected as broken. A quick fix would be to specify the `drawable` attribute instead when scanning lines.

Thank you!

Edit: Here's the broken_drawables result ![broken_drawables](https://user-images.githubusercontent.com/14982166/142259071-41d1d9ac-4704-4f71-ba3a-b983b33a2c63.png)

**Comment by sarsamurmu** [comment]
Thanks for reporting the issue. It should be fixed on the next update.

**Comment by sarsamurmu** [comment]
Fixed in `v3.13.2`
