### ISSUE TITLE
[BUG] One app never shows on the "request icon" dialog

### ISSUE THREAD

**Issue by Donnnno** [zixpo/candybar#66]
Noticed this weird bug because people keep reporting this to me. You can find more about it in these two issues below: 

From the Arcticons issues: https://github.com/Donnnno/Arcticons/issues/623
Delta has this too: https://github.com/Delta-Icons/android/issues/345

**Comment by moertel** [comment]
FWIW, I had a look at this today and found the following:
 * The error only occurs when Premium Requests are disabled
 * It's consistently the first non-themed app (sorted by app name) that is missing

Steps to reproduce:
1. Run CandyBar Dev with default settings in an emulator of your choice
2. Open "Icon Requests" - make note of the first app in the list
3. Set `<bool name="enable_premium_request">false</bool>`
4. Run in the same emulator again
5. Open "Icon Requests" - the app you saw previously now has disappeared

**Comment by Donnnno** [comment]
Very nice that you decided to look into that!
What a very specific thing that causes it to happen tho…

**Comment by sarsamurmu** [comment]
Fixed in `3.14.0`

**Comment by Donnnno** [comment]
Thanks a lot!
