### ISSUE TITLE
Gradle sync failed: Sync failed: reason unknown

### ISSUE THREAD

**Issue by Etny00** [zixpo/candybar#74]
After Android Studio and Gradle Updates to a new version (Gradle PlugIn 7.1.3 and Gradle 7.2), i couldn't sync Gradle anymore with the theme.  It says: "Gradle sync failed: Sync failed: reason unknown" and: Gradle project sync failed. Basic functionality (e.g. editing, debugging) will not work properly. 

I don't know what to do, maybe you can help.

**Comment by moertel** [comment]
If you haven't already, run `File` --> `Invalidate caches` and see if that helps. I'm running on 7.1.3 and 7.2 as well and have no syncing issues.

**Comment by Etny00** [comment]
Unfortunately, it still does not work. Still "Gradle sync failed: Sync failed: reason unknown"

**Comment by Etny00** [comment]
Even if i try to open the template (fresh downloaded) from here, it won't work... it still says: Gradle project sync failed. Basic functionality (e.g. editing, debugging) will not work properly.

Does anyone have any idea what this could be or what i can do?

**Comment by moertel** [comment]
It's highly unlikely that this is a problem with CandyBar. There's something wrong with your local setup, so your best bet is googling the error and following the steps others took to resolve it.

This looks particularly promising, indicating a missing API level installation: https://stackoverflow.com/questions/68173478/gradle-sync-failed-with-reason-unknown-android-studio-4-2-1
