### ISSUE TITLE
Icons don't change color with wallpaper on Graphene Launcher

### ISSUE THREAD

**Issue by Gisbitus** [zixpo/candybar#78]
I'm using the Graphene Launcher and the icons don't change color if I change wallpaper. Since the launcher is not officially supported, I have to use the shortcut maker widget to make app shortcuts. This used to work with the pixel launcher. Is there anything I can do?

**Comment by sarsamurmu** [comment]
I don't think there's anything CandyBar can do. The launcher itself has to update all the icons after a theme change and somehow Graphene launcher can't do that, perhaps the developers didn't implement it.
