### ISSUE TITLE
Icon Request selects next unthemed app instead of the checked one

### ISSUE THREAD

**Issue by wokija** [zixpo/candybar#83]
In the icon request menu, selecting (checking) an unthemed icon to request will send the next one instead. In the icon pack I'm working on, we allow user to send 1 request per release. This ends up not sending what the user wanted.

For example:
Facebook
Instagram
Whatsapp

Checking Instagram and hitting send will gather ComponentInfos for Whatsapp and send that instead.

Tested with last CandyBar release and requests work as expected.

**Comment by sarsamurmu** [comment]
I know the fix. I will release a patch ASAP.

**Comment by Donnnno** [comment]
Thanks a lot!

**Comment by sarsamurmu** [comment]
Fixed!
