### ISSUE TITLE
Icon search bug

### ISSUE THREAD

**Issue by randomvector** [zixpo/candybar#84]
* When a user taps the search icon under "Icons" it doesn't bring up the on screen keyboard. The user will have to also tap the search field to bring up the keyboard. This issue occurs on Android 12.

* Tapping the in app back with the keyboard up will return the user to the icon screen but with no icons loaded.

This has been tested and confirmed on Candybar v3.13.3 and has been reproduced on v3.14.2 by myself and another user in the Telegram group. I've linked a video clip showing the bug using the Candybar Demo.

https://user-images.githubusercontent.com/27604724/170887324-3c7cc59c-99be-478d-b4e1-44d743497671.mp4

**Comment by sarsamurmu** [comment]
It's been there for a long time. I was not able to solve it. Maybe someone can solve it?

**Comment by moertel** [comment]
I found a fix. See linked PR. 👀

**Comment by moertel** [comment]
As to the blank page after using the back button: After lots of trial & error I believe it's a race condition. Performing `addToBackStack` on the fragment was a nice idea but I'm almost sure it's being garbage-collected before it can be displayed again. I can reproduce the blank page 4 out of 5 times but occasionally I still see it when I use the back button in the menu. Also, I can reproduce this with API 28 as well although it behaves slightly differently.

The only meaningful connection I found was this bug (which is said to be fixed) which describes what we're seeing here (IMHO): https://issuetracker.google.com/issues/139095195
