### ISSUE TITLE
Question: Can A Single Icon Be Tied To Multiple Activites/App

### ISSUE THREAD

**Issue by topsy-turvy99** [zixpo/candybar#91]
As a user i see some few icon packs have multiple same icons with different names, so i was wondering can't a single icon be used for multiple apps, so to reduce the icon pack size and obviously the number count, which is misleading 😅

Thank You

**Comment by Donnnno** [comment]
Yes!

**Comment by topsy-turvy99** [comment]
Great Thank You 😇
