### ISSUE TITLE
Icon Requests failing when using Gmail

### ISSUE THREAD

**Issue by randomvector** [zixpo/candybar#97]
There is an issue with Gmail failing to open when sending icon requests via email. I've had multiple users get in touch regarding this issue.

So far it seems to be isolated to the latest version of Gmail (2022.10.02) on devices running Android 12L and 13.

I have been able to test icon requests using Candybar (3.14.2 and 3.15) on Android 12 (stock Pixel 3a) with Gmail versions (2022.09.18 & 2022.10.02) and icon requests are working fine.

Other users on the Telegram channel are reporting this problem too. I've attached a video of bug running on Android 12L

https://user-images.githubusercontent.com/27604724/199336557-d0e9d972-3eba-47ec-a25d-bb135c585a1d.mp4

This is a real problem as first time users not familiar with requesting icons have no indication the request failed and will believe they have requested their chosen icons as shown by the "Already requested". This also affects Premium Icon Requests too. 

If anyone can add more on this issue that would be appreciated as I don't have a device running Android 13.

**Comment by one4studioicons** [comment]
You should change 175th line in the file main/library/src/main/java/candybar/lib/tasks/IconRequestBuilderTask.java with `if (Build.VERSION.SDK_INT < 32) {
                intent.addCategory(Intent.CATEGORY_LAUNCHER);
            }`

**Comment by MiepHD** [comment]
`if (android.os.Build.VERSION.SDK_INT < 32) { intent.addCategory(Intent.CATEGORY_LAUNCHER); }` fixes the issue. I tried it on my device which had this exact issue.
