### ISSUE TITLE
[Request] Please remove the default clock widget from the dashboard 

### ISSUE THREAD

**Issue by Amorphous404** [zixpo/candybar#98]
Please kindly remove the stock widget that is provided within the dashboard, it fills up the add/clutter widgets section with the same looking clock widgets, icon packs that are built with Candy Bar dashboard not the same with blueprint icon packs, most devs don't care on don't know how to remove it, also most devs don't use this method anymore, they instead include custom preset, it will be great if you remove it, to keep the dashboard clean :)

![Screenshot_2022-11-09-14-11-10-04_67d7f8591eff9881972c1169b8bca2d8.jpg](https://user-images.githubusercontent.com/96917972/200784745-ec29dd7a-5e4b-45ca-aaf8-bd90dbbc5032.jpg)

Thank You

**Comment by pashapuma** [comment]
Remove it in your AmdroidManifest

**Comment by topsy-turvy99** [comment]
> Remove it in your AmdroidManifest

I'm asking it as a user, even if i make any changes in the apk to remove it, it will break the licence, even if i learn/manage to do it, i would still have have to redo it everytime.

The reason i requested it, i install a lot of icon packs, as a result my Widget dashboard is filled with these icon packs, carrying the same green clock widget,

Same with Kustom Apps presets, it unnecessaryily  clutter 🥲, i tried requesting the icon pack devs they won't remove it, maybe they don't know how to do it or don't care, idk 🤷‍♂️

**Comment by sarsamurmu** [comment]
Don't worry. I am going to disable these by default in the following updates.
