### ISSUE TITLE
[Request] Please Add Material You Support for candybar dashboard & Provide some options in Settings Page

### ISSUE THREAD

**Issue by Amorphous404** [zixpo/candybar#99]
Please add material you support for candybar dashboard, also provide some necessary toggles similar to Blueprint Dashboard

Blueprint Dashboard Settings:
![Screenshot_2022-11-09-14-40-25-65.jpg](https://user-images.githubusercontent.com/96917972/200788504-cd305c10-1e6c-4448-8ea2-e1c5e009fb04.jpg)

Candbar Dashboard Settings
![Screenshot_2022-11-09-14-39-19-70_c2400d7b87dfbf568623023b91ace1d0.jpg](https://user-images.githubusercontent.com/96917972/200788430-880088d4-25ba-4778-b46c-a0d951103603.jpg)

And if possible make use of M3 design toggles instead of M2.

Thank You

**Comment by Donnnno** [comment]
Got it working without toggles, but it's applies currently automatically on Android 12 & up


![Screenshot_20230518_230208_Arcticons Dark.jpg](https://github.com/zixpo/candybar/assets/31142286/6e2d5634-500c-42d6-9d58-abf12d552d5b)

![Screenshot_20230520_185345_Arcticons Dark.jpg](https://github.com/zixpo/candybar/assets/31142286/61929614-5ac0-4fc8-8e13-3a2a1f363947)
